name: ".NET NuGet"

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'

jobs:
  Deployment:
    uses: Heleonix/workflows/.github/workflows/net-nuget.yml@main
    secrets: inherit